### ISSUE TITLE
unreleased-message not in old versions.

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib.github.com#54]
In #49 we added banner at the top of all the old html pages that is <div tag='unreleased-message'> but there is no CSS for that tag before 2.0.2 and older.  Need to add the following to `_static/mpl.css`

```css 
/* "Go to released version" message. */
#unreleased-message {
  background: #d62728;
  box-sizing: border-box;
  color: #fff;
  font-weight: bold;
  left: 0;
  min-height: 3em;
  padding: 0.7em;
  position: fixed;
  top: 0;
  width: 100%;
  z-index: 10000;
}

#unreleased-message + div {
  margin-top: 3em;
}

#unreleased-message a {
  color: #fff;
  text-decoration:underline;

}
```
